name: aisdecoder
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=4.0.1=py39h0d1d0e5_3
  - attrs=21.2.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h2bbff1b_11
  - bottleneck=1.3.2=py39h7cc1a96_1
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - bzip2=1.0.8=he774522_0
  - c-ares=1.17.1=h2bbff1b_0
  - ca-certificates=2021.9.30=haa95532_1
  - certifi=2021.5.30=py39haa95532_0
  - cffi=1.14.6=py39h0878f49_1
  - cfitsio=3.470=he774522_6
  - chardet=4.0.0=py39hcbf5309_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py39haa95532_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - curl=7.78.0=h86230a5_0
  - cycler=0.10.0=py39haa95532_0
  - daal4py=2021.3.0=py39h757b272_0
  - dal=2021.3.0=haa95532_564
  - debugpy=1.4.1=py39hd77b12b_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - double-conversion=3.1.5=ha925a31_1
  - et_xmlfile=1.1.0=py39haa95532_0
  - expat=2.4.1=h6c2663c_2
  - fiona=1.8.13.post1=py39h758c064_0
  - folium=0.12.0=pyhd8ed1ab_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=h2bbff1b_0
  - gdal=3.0.2=py39hb978731_1
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.6.0=h5770a2b_0
  - gflags=2.2.2=ha925a31_0
  - glog=0.5.0=hd77b12b_0
  - grpc-cpp=1.26.0=h351948d_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=3.1=pyhd3deb0d_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.2.0=py39haa95532_1
  - ipython=7.26.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.2=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39haa95532_0
  - kealib=1.4.14=hde4a422_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - libboost=1.73.0=h6c2663c_11
  - libcurl=7.78.0=h86230a5_0
  - libgdal=3.0.2=ha1b3edf_1
  - libiconv=1.15=h1df5818_7
  - libnetcdf=4.6.1=hf59b723_4
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.2=hb652d5d_1
  - libprotobuf=3.11.2=h7bd577a_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.2.0=hd0e1b90_0
  - libxml2=2.9.12=h0ad7f3c_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.0.1=py39hb82d6ee_0
  - matplotlib-base=3.4.2=py39h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy-base=1.20.3=py39hc2deb75_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1l=h2bbff1b_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py38haa95532_0
  - postgresql=12.2=hb652d5d_1
  - proj=6.2.1=h9f7ef89_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - pyarrow=4.0.1=py39h953b917_3
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py39h593ac45_1
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.6=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=228=py39hbaba5e8_1
  - pyzmq=22.2.1=py39hd77b12b_1
  - re2=2020.11.01=hd77b12b_1
  - requests=2.26.0=pyhd8ed1ab_0
  - rtree=0.9.7=py39h2eaa2aa_1
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scikit-learn-intelex=2021.3.0=py39haa95532_0
  - scipy=1.7.1=py39hbe87c03_2
  - setuptools=52.0.0=py39haa95532_0
  - shapely=1.7.1=py39h06580b3_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2021.3.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.2.9=hf7ce2e6_0
  - tk=8.6.11=h2bbff1b_0
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h5d7bf9c_0
  - uriparser=0.9.3=h33f27b4_1
  - urllib3=1.26.7=pyhd8ed1ab_0
  - utf8proc=2.6.1=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39h2bbff1b_0
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - bitarray==2.3.2
    - numpy==1.21.2
    - pandas==1.3.2
    - pyais==1.6.1
    - pynmea==0.6.0
    - pynmea2==1.18.0
    - pyqt5==5.15.4
    - pyqt5-plugins==5.15.4.2.2
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyqt5-tools==5.15.4.3.2
    - python-dotenv==0.19.1
    - qt5-applications==5.15.2.2.2
    - qt5-tools==5.15.2.1.2
prefix: C:\Anaconda\envs\aisdecoder
